server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  #配置远程git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EverythingStart01/springcloud-config.git