server:
  port: 8009

eureka:
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    service-url: #监控页面
      #单机：http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群：
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7001.com:7001/eureka/